# Generated by Django 5.2 on 2026-04-24 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="student_id_num_num",
            new_name="student_id_num",
        ),
    ]
